import torch
import torch.nn as nn

class CausalPositionalEncoding(nn.Module):
    """
    Standard 1D positional encoding to inject temporal ordering information 
    into the sequence of frames before processing them. 
    """
    def __init__(self, d_model, max_len=100):
        super(CausalPositionalEncoding, self).__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-torch.log(torch.tensor(10000.0)) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe)

    def forward(self, x):
        """
        x: (B, T, C)
        Returns: x + pe
        """
        B, T, C = x.shape
        return x + self.pe[:T, :].unsqueeze(0)


class BandedCausalTemporalEncoder(nn.Module):
    """
    Banded Causal Temporal Encoder.
    Operates on the spatial-pooled features generated by the Backbone.
    
    Instead of LSTMs, this uses a Transformer Encoder with a strict *causal mask*. 
    A causal mask ensures that processing for frame `t` ONLY attends to `t` and 
    previous frames, strictly preventing data leakage from the future in a surgical setting.
    """
    def __init__(self, d_model=1024, nhead=8, num_layers=3, dim_feedforward=2048, dropout=0.1):
        super(BandedCausalTemporalEncoder, self).__init__()
        
        self.pos_encoder = CausalPositionalEncoding(d_model=d_model)
        
        # standard transformer encoder layer
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, 
            nhead=nhead, 
            dim_feedforward=dim_feedforward, 
            dropout=dropout, 
            batch_first=True # We will pass (B, T, C) into the transformer
        )
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

    def generate_causal_mask(self, sz):
        """
        Generates an upper-triangular matrix of -inf, with zeros on diag/lower triangle.
        This forces the self-attention to only look back in time.
        """
        # torch.triu generates upper triangular. True where row < col (i.e. future)
        mask = (torch.triu(torch.ones(sz, sz)) == 1).transpose(0, 1)
        mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
        return mask

    def forward(self, x):
        """
        Args:
            x: (B, T, NumSpatialTokens, Channels). 
               e.g., from Swin-B: (2, 8, 144, 1024)
        Returns:
            encoded_frames: (B, T, d_model). Summarized temporal state per frame.
        """
        B, T, L, C = x.shape
        
        # For the temporal encoder, we want to summarize the spatial information first 
        # before running it through time. We can achieve this via average pooling.
        # So we pool the 144 tokens down to 1 feature vector per frame.
        # x_pooled: (B, T, C)
        x_pooled = x.mean(dim=2) 
        
        # Inject temporal position info
        x_pos = self.pos_encoder(x_pooled)
        
        # Create causal mask (T x T)
        causal_mask = self.generate_causal_mask(T).to(x.device)
        
        # Transformer pass
        # The transformer output naturally matches the causal masking, meaning 
        # out[:, t, :] represents the historical context up to frame t.
        out = self.transformer_encoder(x_pos, mask=causal_mask) # (B, T, C)
        
        return out

if __name__ == "__main__":
    print("--- Testing Banded Causal Temporal Encoder ---")
    model = BandedCausalTemporalEncoder().cuda()
    
    # Dummy features representing Swin-B output (B=2, T=8, Spatial=144, C=1024)
    dummy_feats = torch.randn(2, 8, 144, 1024).cuda()
    
    encoded = model(dummy_feats)
    print(f"Input Feature Shape: {dummy_feats.shape}")
    print(f"Temporal Encoded Shape: {encoded.shape} (Expected: B, T, d_model = 2, 8, 1024)")
    print("--- Test Passed ---")
